//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Teams.Apps.Timesheet.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Teams.Apps.Timesheet.Common.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action required.
        /// </summary>
        public static string ActionRequiredSubTitle {
            get {
                return ResourceManager.GetString("ActionRequiredSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved.
        /// </summary>
        public static string ApprovedStatus {
            get {
                return ResourceManager.GetString("ApprovedStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string CommentLabel {
            get {
                return ResourceManager.GetString("CommentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update timesheet.
        /// </summary>
        public static string FillTimesheetButton {
            get {
                return ResourceManager.GetString("FillTimesheetButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s timesheet time!.
        /// </summary>
        public static string FillTimesheetReminderCardTitle {
            get {
                return ResourceManager.GetString("FillTimesheetReminderCardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hours.
        /// </summary>
        public static string HoursLabel {
            get {
                return ResourceManager.GetString("HoursLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review.
        /// </summary>
        public static string ManagerReminderCardButtonText {
            get {
                return ResourceManager.GetString("ManagerReminderCardButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action required.
        /// </summary>
        public static string ManagerReminderCardSubTitle {
            get {
                return ResourceManager.GetString("ManagerReminderCardSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timesheet updates.
        /// </summary>
        public static string ManagerReminderCardTitle {
            get {
                return ResourceManager.GetString("ManagerReminderCardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have {0} updates requiring your review..
        /// </summary>
        public static string PendingRequests {
            get {
                return ResourceManager.GetString("PendingRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        public static string ProjectLabel {
            get {
                return ResourceManager.GetString("ProjectLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected.
        /// </summary>
        public static string RejectedStatus {
            get {
                return ResourceManager.GetString("RejectedStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have {0} pending requests for timesheet approval..
        /// </summary>
        public static string RequestsReminderCardText {
            get {
                return ResourceManager.GetString("RequestsReminderCardText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timesheet update approved.
        /// </summary>
        public static string TimesheetApprovedCardTitle {
            get {
                return ResourceManager.GetString("TimesheetApprovedCardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timesheet update rejected.
        /// </summary>
        public static string TimesheetRejectedCardTitle {
            get {
                return ResourceManager.GetString("TimesheetRejectedCardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timesheet requests.
        /// </summary>
        public static string TimesheetRequestsCardTitle {
            get {
                return ResourceManager.GetString("TimesheetRequestsCardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View requests.
        /// </summary>
        public static string ViewRequestButton {
            get {
                return ResourceManager.GetString("ViewRequestButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View timesheet.
        /// </summary>
        public static string ViewTimesheetButtonText {
            get {
                return ResourceManager.GetString("ViewTimesheetButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi! I&apos;m the Time Tally bot!
        ///
        ///
        ///I&apos;m here to help you update your timesheet. Here&apos;s what to do:
        ///
        ///
        ///• Select **Update timesheet** whenever you&apos;re ready to save or submit hours.
        ///
        ///
        ///• Make sure you&apos;ve entered all your hours for any given day before submitting your updates..
        /// </summary>
        public static string WelcomeCardIntro {
            get {
                return ResourceManager.GetString("WelcomeCardIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timesheet made easy.
        /// </summary>
        public static string WelcomeCardSubtitle {
            get {
                return ResourceManager.GetString("WelcomeCardSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi, you are on time!.
        /// </summary>
        public static string WelcomeCardTitle {
            get {
                return ResourceManager.GetString("WelcomeCardTitle", resourceCulture);
            }
        }
    }
}
